[package]
name = "eva01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anchor-lang = { git = "https://github.com/mrgnlabs/anchor.git", rev = "fdcf299dc55ecf7cfa8c4d598aecb1363b99c02d" }
anchor-spl = { git = "https://github.com/mrgnlabs/anchor.git", features = [
    "token_2022",
], rev = "fdcf299dc55ecf7cfa8c4d598aecb1363b99c02d" }
anchor-client = { git = "https://github.com/mrgnlabs/anchor.git", rev = "fdcf299dc55ecf7cfa8c4d598aecb1363b99c02d", features = [
    "async",
] }

anyhow = "1.0.79"
backoff = { version = "0.4.0", features = ["futures", "tokio"] }
bincode = "1.3.3"
bytemuck = "1.14.0"
bytes = "1.5.0"
clap = { version = "4.5.4", features = ["derive"] }
crossbeam = { version = "0.8.4", features = ["crossbeam-channel"] }
dirs = "4.0.0"
env_logger = "0.11.3"
fixed = "1.24.0"
fixed-macro = "1.2.0"
futures = "0.3.30"
futures-sink = "0.3.30"
jupiter-swap-api-client = "0.1.0"
lazy_static = "1.5.0"
log = "0.4.21"
marginfi = { git = "https://github.com/mrgnlabs/marginfi-v2", features = [
    "mainnet-beta",
    "client",
    "no-entrypoint",
] }

num-traits = "0.2.18"
rayon = "1.10.0"
serde = "1.0.197"
serde_json = "1.0.116"
sha2 = "0.10.8"
solana-account-decoder = "1.18.17"
solana-client = "1.18.17"
solana-program = "1.18.17"
solana-rpc-client-api = "1.18.17"
solana-sdk = "1.18.17"
solana-address-lookup-table-program = "1.18.17"
spl-associated-token-account = "2.0.0"
spl-token = "=4.0.0"
thiserror = "1.0.56"
tokio = { version = "1.35.1", features = ["rt", "macros"] }
toml = "0.8.12"
tonic = "0.10.2"
tonic-health = "0.10.2"
yellowstone-grpc-client = { git = "https://github.com/mrgnlabs/yellowstone-grpc", branch = "1.18.17" }
yellowstone-grpc-proto = { git = "https://github.com/mrgnlabs/yellowstone-grpc", branch = "1.18.17" }
jito-protos = { git = "https://github.com/mrgnlabs/jito-rs", branch = "1.18.17" }
jito-searcher-client = { git = "https://github.com/mrgnlabs/jito-rs", branch = "1.18.17" }
switchboard-on-demand = "0.1.15"
switchboard-on-demand-client = "0.1.7"
chrono = "0.4.38"
hex = "0.4.3"
url = "2.5.2"

[profile.release]
opt-level = 3
lto = true
target-cpu = "native"
